AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  backend deployment

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 30
    Environment:
      Variables:
        ARTIFACTS_TABLE_NAME: !Ref ArtifactsTable


Resources:
  ArtifactsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Artifacts
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
        - AttributeName: name
          AttributeType: S
        - AttributeName: artifact_type
          AttributeType: S
        - AttributeName: artifact_id
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: NameIndex
          KeySchema:
            - AttributeName: name
              KeyType: HASH
            - AttributeName: artifact_id
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: TypeIndex
          KeySchema:
            - AttributeName: artifact_type
              KeyType: HASH
            - AttributeName: artifact_id
              KeyType: RANGE
          Projection:
            ProjectionType: ALL

  HandlerFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: backend/
      Handler: app.lambda.handler
      Runtime: python3.12
      Architectures:
        - x86_64
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ArtifactsTable
      Events:
        RootPath:
          Type: Api
          Properties:
            Path: /
            Method: ANY
        ProxyPath:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  BackendApiURL:
    Description: "API Gateway endpoint URL for Prod stage for backend deployment"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/Prod/"
  HandlerFunction:
    Description: "HandlerFunction Lambda Function ARN"
    Value: !GetAtt HandlerFunction.Arn
  HandlerFunctionIAMRole:
    Description: "Implicit IAM Role created for HandlerFunction"
    Value: !GetAtt HandlerFunctionRole.Arn
  ArtifactsTableName:
    Description: "DynamoDB Artifacts Table Name"
    Value: !Ref ArtifactsTable
